language: node_js
node_js:
- '12'
after_success:
- bash <(curl -s https://codecov.io/bash)
- yarn lint
deploy:
  provider: npm
  email: ci@terascope.io
  api_key:
   secure: "ADD API KEY HERE"
  on:
    branch: master
    tags: true
