language: node_js
node_js:
- '8'
after_install:
- yarn build
after_success:
- bash <(curl -s https://codecov.io/bash)
- yarn lint || echo "Let's show the lint output here but we don't want it cause a failure yet"
deploy:
  provider: npm
  email: peter@terascope.io
  api_key:
   secure: "ADD API KEY HERE"
  on:
    branch: master
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
